config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only:[:index, :new, :create, :destroy],
  path: '/admin/resumes'
  
  namespace :admin do
    resources :videos
    resources :prods
    resources :resumes
    root to: "videos#index"
  end

  root 'pages#home'
  get 'home' =>'pages#home'
  get 'about' => 'pages#about'
  get 'videos' => 'videos#index'
  get 'videos/:slug' => 'videos#show', as: :video

end

app/models/concerns/mp3.rb
require 'mime/types'

class Mp3 < ActiveRecord::Base
  belongs_to :prod
  
  has_attached_file :mp3
  validates_attachment :mp3, 
    :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, 
    :file_name => { :matches => [/mp3\Z/] }
    
  def set_mime_type(data)
    data.content_type = MIME::Types.type_for(data.original_filename).to_s
    self.mp3 = data
  end
end

app/models/prod.rb
class Prod < ActiveRecord::Base
  belongs_to :video
  has_many :attachment

  has_attached_file :mp3
  validates_attachment :mp3, 
    :content_type => { :content_type => ["audio/mp3"] }, 
    :file_name => { :matches => [/mp3\Z/] }
end

app/models/resume.rb
class Resume < ActiveRecord::Base
    belongs_to :prod

    mount_uploader:attachment,
    AttachmentUploader
    validates :name, presence:true
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300#", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :prods
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: ENV.fetch("ADMIN_NAME"), password: ENV.fetch("ADMIN_PASSWORD")
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/prods_controller.rb
module Admin
  class ProdsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Prod.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Prod.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/resumes_controller.rb
module Admin
  class ResumesController < Admin::ApplicationController
    
  end
end

app/controllers/admin/videos_controller.rb
module Admin
  class VideosController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Video.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Video.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
        @resumes = Resume.all

  end

  def about
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
        @resume = Resume.new
  end

  def create
        @resume = Resume.new(resume_params)
        
      if @resume.save
        redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
        
      else
        render "new"
      end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: "The resume #{@resume.name} has been deleted."
  end
  
  private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  	@videos = Video.all
  	  	@mp3s = Mp3.all
  end
  
  def show
    @video = Video.find_by_slug(params[:slug])
    
    if @video.nil?
      redirect_to root_path
    end
  	@videos = Video.all
  	@prods = Prod.all
  	@mp3s = Mp3.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(title)
        base_title = "Holdup2x Music"
        
        if (title.empty?)
            base_title
            
        else
            "#{title} - #{base_title}"
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/fields/paperclip_field/_form.html.erb
<div class="field-unit__label">
	<%= f.label field.attribute %>
</div>

<div class="field-unit__field">
<%= f.file_field field.attribute %>
</div>

<div class="field">
	<%= f.label :mp3 %>
</div>

<div class="field">
<%= f.file_field :mp3 %>
</div>

app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.medium %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Roboto:700,300,400' rel='stylesheet' type='text/css'>
</head>

<body>

<%= render 'layouts/partials/nav' %>

  <div class="container" id='content'>
<%= yield %>
    <div class="download">
      <a href="http://kolber.github.com/audiojs/audiojs.zip" class="button"><em>Download</em> audio.js</a>
    </div>
<%= render 'layouts/partials/footer' %>
  </div>



</body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer id="main-footer" class="text-center">
  <p>Built By Franky With Ruby On Rails - &copy; 2016 All Rights Reserved.</p>
</footer>

app/views/layouts/partials/_nav.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" id="main-menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">HOLDUP2X MUSIC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
      <li><a href="<%= videos_path %>">Videos</a></li>
      <li><a href="<%= about_path %>">About</a></li>
      <li><form class="navbar-form navbar-right">
          <input type="text" class="form-control" id="barre_recherche" placeholder="Search...">
          </form></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    </div>   
<div>
  <audio src="/mp3/juicy.mp3" preload="auto" />
</div>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<h1>About ok ok<h1>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>

<div class="jumbotron">
<h1 style="text-align: center">Welcome to <br>Holdup2X music producer!</h1>
</div>

	<div class="row">

		  <div class="col-sm-4 col-md-3">
		    <div class="thumbnail">
		        <h2>Soza - H.T.U.L</h2>
             <iframe class= "img-circle" width="200" height="200" src="https://www.youtube.com/embed/IuA8kwSSkdg" 
             frameborder="0" allowfullscreen></iframe>
		      <div class="caption">
		        <h3>Poduced by HOLDUP2X </h3>
		      </div>
		    </div>
		  </div>

	
<table id="table_prod" class = "table table-bordered table-striped" 
style="width: 400px;">
	<thead>.
		<tr>
		<th>NAME</th>
		<th>PROD</th>
		</tr>
		</thead>
		
		
		<tbody>
		<% @resumes.each do |resume| %>
		
		
		<tr>
		<td><%= resume.name %></td>
		<td><audio src ="<%= resume.attachment_url %>" controls></audio></td>
		</tr>
		
		<% end %>
	</tbody>
</table>

	</div>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
<div class = "alert alert-info" >
<%= flash[:notice] %>
</div>
<% end %>


<br/>


<%= link_to "New Resume", new_resume_path, class: "btn btn-primary" %>
<br/>
<br/>


<table class = "table table-bordered table-striped">
<thead>.
<tr>
<th>Name</th>
<th>Download Link</th>
<th> </th>
</tr>
</thead>


<tbody>
<% @resumes.each do |resume| %>


<tr>
<td><%= resume.name %></td>
<td><audio src ="<%= resume.attachment_url %>" controls></audio></td>
<td><%= button_to "Delete", resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
</tr>

<% end %>
</tbody>
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
<div class = "alert alert-error" >


<ul>
<% @resume.errors.full_messages.each do |msg| %>
<li ><%= msg %></li>
<% end %>
</ul>


</div>
<% end %>


<div class = "well">
<%= form_for @resume, html: { multipart: true } do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :attachment %>
<%= f.file_field :attachment %>
<%= f.submit "Save", class: "btn btn-primary" %>
<% end %>
</div >

app/views/videos/index.html.erb
<h1><%= @videos.count %> Styles Musicaux Disponible !</h1>

<p>Enjoy ! </p>

	<div class="row">
	   <% for video in @videos %>
		  <div class="col-sm-4 col-md-3">
		    <div class="thumbnail">
		      <%= image_tag video.image.url(:medium), alt: video.title, class: "img-circle" %>
		      <div class="caption">
		        <h3><%= video.title %></h3>
		        <p><%= truncate(video.descrition) %></p>
		        <a href="<%= video_path(video.slug) %>" class="btn btn-primary", role="button">Click</a>
		      </div>
		    </div>
		  </div>
	  <% end %>
	  	  	<audio src="www.youtube.com/embed/TFQV8C04dgU" controls></audio>
	</div>

app/views/videos/show.html.erb
<h1><%= @prods.count %> Prods Disponible !</h1>


    <article>
        <h2><%= @video.title %></h2>
    	<%= image_tag @video.image.url(:medium), alt: @video.title %>
        <p><%= @video.descrition %></p>
           <audio src="<%= :mp3s %>" controls></audio>
      
        <hr>
        
        <section>
            <% if @video.prods.empty? %>
            <p>Aucune prod disponible.</p>
            <% else %>
                <%= @video.prods.each do |prod| %>
                <h3><%= prod.title %></h3>
                <p><%= prod.description %></p>
                <% end %>
            <% end %>
        </section>
    </article>
	